apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ecommerce
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'ecommerce-app'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: ecommerce
          - source_labels: [__meta_kubernetes_pod_container_name]
            action: keep
            regex: node-exporter
          - source_labels: [__address__, __meta_kubernetes_pod_container_port_number]
            action: replace
            target_label: __address__
            regex: (.+):9100
            replacement: ${1}:9100

